name = "Erjulix"
uuid = "de6a4c11-948d-47de-a21c-147f86858631"
authors = ["Paul Bayer <Paul.Bayer@gleichsam.de>"]
version = "0.1.0"

[deps]
ErlangTerm = "6cf46ab0-e18c-5424-9784-c70c22e5b0c7"

[compat]
julia = "1.6"
ErlangTerm = "0.1"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Documenter", "SafeTestsets"]
